try:
    result=45/0
except:
    print('error occured')
finally:
    print('finally here')
print('Done')